version: '3.9'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/opt
    depends_on:
      - db
  
  db:
    image: postgres:14.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
volumes:
  db-data:
